import { useEffect, useState } from 'react'
import AdminJobCard from '../../components/admin/AdminJobCard'
import AdminNavigation from '../../components/admin/AdminNavigation'
import adminService from '../../services/adminService'

function Jobs() {
  const [jobs, setJobs] = useState([]); const [loading, setLoading] = useState(true); const [actionId, setActionId] = useState(null); const [pageError, setPageError] = useState(''); const [successMessage, setSuccessMessage] = useState('')
  const loadJobs = async () => { setLoading(true); setPageError(''); try { const response = await adminService.getJobs(); setJobs(Array.isArray(response) ? response : response?.items || []) } catch (error) { setPageError(error.response?.data?.message || error.response?.data?.title || 'Unable to load jobs.') } finally { setLoading(false) } }
  useEffect(() => { void Promise.resolve().then(loadJobs) }, [])
  const handleToggleStatus = async (job) => { const action = job.isActive ? 'deactivate' : 'activate'; if (!window.confirm(`Are you sure you want to ${action} "${job.title}"?`)) return; setActionId(job.id); setPageError(''); setSuccessMessage(''); try { if (job.isActive) await adminService.deactivateJob(job.id); else await adminService.activateJob(job.id); setJobs((previousJobs) => previousJobs.map((item) => item.id === job.id ? { ...item, isActive: !job.isActive } : item)); setSuccessMessage(job.isActive ? 'Job deactivated successfully.' : 'Job activated successfully.') } catch (error) { setPageError(error.response?.data?.message || error.response?.data?.title || 'Unable to update job status.') } finally { setActionId(null) } }
  return <div className="min-h-screen bg-slate-50"><AdminNavigation /><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="mb-8"><p className="text-sm font-bold uppercase tracking-wider text-blue-600">Administration</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">Job Management</h1><p className="mt-2 text-slate-600">Review job postings and control their public availability.</p></div>{pageError && <div className="mb-6 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-medium text-rose-700">{pageError}</div>}{successMessage && <div className="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-700">{successMessage}</div>}{loading ? <div className="rounded-2xl bg-white p-10 text-center shadow-sm"><p className="text-slate-600">Loading jobs...</p></div> : jobs.length === 0 ? <div className="rounded-2xl bg-white p-10 text-center shadow-sm"><h2 className="text-xl font-bold text-slate-900">No jobs found</h2><p className="mt-2 text-slate-600">Job postings will appear here once recruiters create them.</p></div> : <section className="space-y-4" aria-label="Jobs">{jobs.map((job) => <AdminJobCard key={job.id} job={job} onToggleStatus={handleToggleStatus} actionLoading={actionId === job.id} />)}</section>}</main></div>
}

export default Jobs
