import { useEffect, useState } from 'react'
import AdminNavigation from '../../components/admin/AdminNavigation'
import UserCard from '../../components/admin/UserCard'
import { useAuth } from '../../context/AuthContext'
import adminService from '../../services/adminService'

function Users() {
  const { user: currentUser } = useAuth(); const [users, setUsers] = useState([]); const [loading, setLoading] = useState(true); const [actionId, setActionId] = useState(null); const [pageError, setPageError] = useState(''); const [successMessage, setSuccessMessage] = useState('')
  const loadUsers = async () => { setLoading(true); setPageError(''); try { const response = await adminService.getUsers(); setUsers(Array.isArray(response) ? response : response?.items || []) } catch (error) { setPageError(error.response?.data?.message || error.response?.data?.title || 'Unable to load users.') } finally { setLoading(false) } }
  useEffect(() => { void Promise.resolve().then(loadUsers) }, [])
  const handleToggleStatus = async (selectedUser) => { if (String(selectedUser.id) === String(currentUser?.userId)) { setPageError('You cannot change the status of your own account.'); return }; const action = selectedUser.isBlocked ? 'unblock' : 'block'; if (!window.confirm(`Are you sure you want to ${action} ${selectedUser.name}?`)) return; setActionId(selectedUser.id); setPageError(''); setSuccessMessage(''); try { if (selectedUser.isBlocked) await adminService.unblockUser(selectedUser.id); else await adminService.blockUser(selectedUser.id); setUsers((previousUsers) => previousUsers.map((item) => item.id === selectedUser.id ? { ...item, isBlocked: !selectedUser.isBlocked } : item)); setSuccessMessage(selectedUser.isBlocked ? 'User unblocked successfully.' : 'User blocked successfully.') } catch (error) { setPageError(error.response?.data?.message || error.response?.data?.title || (selectedUser.isBlocked ? 'Unable to unblock user.' : 'Unable to block user.')) } finally { setActionId(null) } }
  return <div className="min-h-screen bg-slate-50"><AdminNavigation /><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="mb-8"><p className="text-sm font-bold uppercase tracking-wider text-blue-600">Administration</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-900">User Management</h1><p className="mt-2 text-slate-600">Review account status and manage platform access.</p></div>{pageError && <div className="mb-6 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-medium text-rose-700">{pageError}</div>}{successMessage && <div className="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-700">{successMessage}</div>}{loading ? <div className="rounded-2xl bg-white p-10 text-center shadow-sm"><p className="text-slate-600">Loading users...</p></div> : users.length === 0 ? <div className="rounded-2xl bg-white p-10 text-center shadow-sm"><h2 className="text-xl font-bold text-slate-900">No users found</h2><p className="mt-2 text-slate-600">Users will appear here once accounts are created.</p></div> : <section className="space-y-4" aria-label="Users">{users.map((item) => <UserCard key={item.id} user={item} onToggleStatus={handleToggleStatus} actionLoading={actionId === item.id} isCurrentUser={String(item.id) === String(currentUser?.userId)} />)}</section>}</main></div>
}

export default Users
